### ISSUE TITLE
'Something went wrong' when trying to review the request

### ISSUE THREAD

**Issue by christinach** [pulibrary/approvals#908]
### Expected behavior
The user should be able to review the request.

### Actual behavior
I’m trying to access an Absence and Travel Request (ID 10934) that I received a notification about this morning. When I try to review the request, though, I receive the error below stating that something went wrong. I have no other issues logging in or seeing my home screen.
Thanks,
Jen

### Impact of this bug
User cannot complete their work.

### Honeybadger link and code snippet, if applicable

[Honeybadger link](https://app.honeybadger.io/projects/67941/faults/97676032)

### Implementation notes, if any
LSupport ticket number (INC0508962)

**Comment by maxkadel** [comment]
It appears that since July 9, 2023, there have been a few TravelRequests created with estimates with nil values, including `cost_type` (which is the absent value raising the error). 

So my first question is, what changed to allow for creation of empty Estimates, which appears to be a new issue? 

Second, what should we do with the 4 existing estimates that only have nil or default (created at etc) data?

**Comment by maxkadel** [comment]
It seems like the bug allowing for submission of empty expenses may have arisen in conjunction with https://github.com/pulibrary/approvals/pull/900.

**Comment by maxkadel** [comment]
Closed by https://github.com/pulibrary/approvals/pull/911
